### ISSUE TITLE
Add admin page to manage inventory and price and databases in general

### ISSUE THREAD

**Issue by Kyrne** [ivario123/D0018E-e-comerce#14]

**Comment by ivajon** [comment]
I think we should split this into multiple issues:

- Add page to manage a single product
- Add page to manage all products ( make individual product modification on ^ page ), here we may provide a list view of all products 
and add a toggle to display it or not
- Add page to manage a single user
- Add page to manage all users ...

**Comment by ivajon** [comment]
Replaced by #37  #38  #36
